/* ==========================================================================
   hormones.js — how a food moves your hormones

   For a portion of any food this works out the likely effect on the hormones
   people ask about — insulin, the fullness and hunger hormones, cortisol,
   adrenaline, testosterone, estrogen, thyroid, melatonin, IGF-1, aldosterone
   and vitamin D — from three things it knows about the food:

     nutrients    glycemic load, protein, fibre, free sugar, zinc, iodine …
     compounds    caffeine, alcohol, soy isoflavones, glycyrrhizin …
     ingredients  flax, mint, hops, cinnamon, green tea, cocoa, cruciferous
                  vegetables, whey, oats, oily fish, adaptogens such as
                  ashwagandha — detected from the ingredient list (packaged
                  food) or the name (whole food)

   Every reason carries an evidence grade and its sources. "No effect" findings
   are reported too: soy does not lower testosterone, and saying so is as
   useful as any warning. Effects are for an average adult and are education,
   not medical advice.
   ========================================================================== */
(function () {
  'use strict';

  /* Extra sources, merged into Body.SOURCES so every sheet can cite them. */
  const SOURCES = {
    'holt-1997': 'Holt SH et al. (1997). An insulin index of foods: the insulin demand generated by 1000-kJ portions of common foods. Am J Clin Nutr 66(5):1264–1276.',
    'allen-2013': 'Allen RW et al. (2013). Cinnamon use in type 2 diabetes: an updated systematic review and meta-analysis. Ann Fam Med 11(5):452–459.',
    'chambers-2015': 'Chambers ES et al. (2015). Effects of targeted delivery of propionate to the human colon on appetite regulation, body weight maintenance and adiposity in overweight adults. Gut 64(11):1744–1754.',
    'dimeglio-2000': 'DiMeglio DP, Mattes RD (2000). Liquid versus solid carbohydrate: effects on food intake and body weight. Int J Obes 24(6):794–800.',
    'blom-2006': 'Blom WA et al. (2006). Effect of a high-protein breakfast on the postprandial ghrelin response. Am J Clin Nutr 83(2):211–220.',
    'teff-2004': 'Teff KL et al. (2004). Dietary fructose reduces circulating insulin and leptin, attenuates postprandial suppression of ghrelin, and increases triglycerides in women. J Clin Endocrinol Metab 89(6):2963–2972.',
    'ludwig-1999': 'Ludwig DS et al. (1999). High glycemic index foods, overeating, and obesity. Pediatrics 103(3):e26.',
    'badrick-2008': 'Badrick E et al. (2008). The relationship between alcohol consumption and cortisol secretion in an aging cohort. J Clin Endocrinol Metab 93(3):750–757.',
    'stewart-1987': 'Stewart PM et al. (1987). Mineralocorticoid activity of liquorice: 11-beta-hydroxysteroid dehydrogenase deficiency comes of age. Lancet 2(8563):821–824.',
    'chandrasekhar-2012': 'Chandrasekhar K et al. (2012). A prospective, randomized double-blind, placebo-controlled study of safety and efficacy of a high-concentration full-spectrum extract of ashwagandha root in reducing stress and anxiety in adults. Indian J Psychol Med 34(3):255–262.',
    'lopresti-2019': 'Lopresti AL et al. (2019). A randomized, double-blind, placebo-controlled, crossover study examining the hormonal and vitality effects of ashwagandha in aging, overweight males. Am J Mens Health 13(2):1557988319835985.',
    'robertson-1978': 'Robertson D et al. (1978). Effects of caffeine on plasma renin activity, catecholamines and blood pressure. N Engl J Med 298(4):181–186.',
    'caronia-2013': 'Caronia LM et al. (2013). Abrupt decrease in serum testosterone levels after an oral glucose load in men: implications for screening for hypogonadism. Clin Endocrinol 78(2):291–296.',
    'grant-2010': 'Grant P (2010). Spearmint herbal tea has significant anti-androgen effects in polycystic ovarian syndrome. A randomized controlled trial. Phytother Res 24(2):186–188.',
    'nowak-2007': 'Nowak DA et al. (2007). The effect of flaxseed supplementation on hormonal levels associated with polycystic ovarian syndrome: a case study. Curr Top Nutraceutical Res 5(4):177–181.',
    'pilz-2011': 'Pilz S et al. (2011). Effect of vitamin D supplementation on testosterone levels in men. Horm Metab Res 43(3):223–225.',
    'mansoori-2020': 'Mansoori A et al. (2020). Effect of fenugreek extract supplement on testosterone levels in male: a meta-analysis of clinical trials. Phytother Res 34(7):1550–1555.',
    'qureshi-2014': 'Qureshi A et al. (2014). A systematic review on the herbal extract Tribulus terrestris and the roots of its putative aphrodisiac and performance enhancing effect. J Diet Suppl 11(1):64–79.',
    'dorgan-2001': 'Dorgan JF et al. (2001). Serum hormones and the alcohol–breast cancer association in postmenopausal women. J Natl Cancer Inst 93(9):710–715.',
    'milligan-1999': 'Milligan SR et al. (1999). Identification of a potent phytoestrogen in hops (Humulus lupulus L.) and beer. J Clin Endocrinol Metab 84(6):2249–2252.',
    'phipps-1993': 'Phipps WR et al. (1993). Effect of flax seed ingestion on the menstrual cycle. J Clin Endocrinol Metab 77(5):1215–1219.',
    'gaskins-2009': 'Gaskins AJ et al. (2009). Effect of daily fiber intake on reproductive function: the BioCycle Study. Am J Clin Nutr 90(4):1061–1069.',
    'fowke-2000': 'Fowke JH et al. (2000). Brassica vegetable consumption shifts estrogen metabolism in healthy postmenopausal women. Cancer Epidemiol Biomarkers Prev 9(8):773–779.',
    'messina-2006': 'Messina M, Redmond G (2006). Effects of soy protein and soybean isoflavones on thyroid function in healthy adults and hypothyroid patients: a review of the relevant literature. Thyroid 16(3):249–258.',
    'felker-2016': 'Felker P et al. (2016). Concentrations of thiocyanate and goitrin in human plasma, their precursor concentrations in brassica vegetables, and associated potential risk for hypothyroidism. Nutr Rev 74(4):248–258.',
    'burke-2015': 'Burke TM et al. (2015). Effects of caffeine on the human circadian clock in vivo and in vitro. Sci Transl Med 7(305):305ra146.',
    'howatson-2012': 'Howatson G et al. (2012). Effect of tart cherry juice (Prunus cerasus) on melatonin levels and enhanced sleep quality. Eur J Nutr 51(8):909–916.',
    'romo-ventura-2020': 'Romo Ventura E et al. (2020). Association of dietary intake of milk and dairy products with blood concentrations of insulin-like growth factor 1 (IGF-1) in Bavarian adults. Eur J Nutr 59(4):1413–1420.',
    'efsa-iodine-ul': 'EFSA Scientific Committee on Food (2002). Opinion on the tolerable upper intake level of iodine (600 µg/day for adults).'
  };

  /* The hormones shown, in display order. `goodWhen`: which direction helps. */
  const LIST = [
    { k: 'insulin',     label: 'Insulin',              icon: 'drop',    role: 'Moves sugar out of the blood into cells. Big, frequent spikes favour fat storage and rebound hunger.' },
    { k: 'satiety',     label: 'Fullness (GLP-1, PYY)', icon: 'gut',    role: 'Gut hormones that tell the brain you have eaten enough.' },
    { k: 'ghrelin',     label: 'Hunger (ghrelin)',     icon: 'gut',     role: 'The hunger hormone; it rises before meals and falls after them.' },
    { k: 'cortisol',    label: 'Cortisol',             icon: 'brain',   role: 'The main stress hormone; it raises blood sugar and blood pressure.' },
    { k: 'adrenaline',  label: 'Adrenaline',           icon: 'heart',   role: 'Fight-or-flight hormone: heart rate, alertness, fat release.' },
    { k: 'testosterone', label: 'Testosterone',        icon: 'hormone', role: 'Muscle, libido, mood and energy — in men and, at lower levels, women.' },
    { k: 'estrogen',    label: 'Estrogen',             icon: 'hormone', role: 'Cycle, bones and heart in women; also present and needed in men.' },
    { k: 'thyroid',     label: 'Thyroid (T3/T4)',      icon: 'thyroid', role: 'Sets your metabolic rate; built from iodine and activated with selenium.' },
    { k: 'melatonin',   label: 'Melatonin (sleep)',    icon: 'brain',   role: 'Darkness hormone that times sleep.' },
    { k: 'igf1',        label: 'IGF-1 (growth)',       icon: 'muscle',  role: 'Growth signal for muscle and tissue repair; very high long-term levels are linked to some cancers.' },
    { k: 'aldosterone', label: 'Aldosterone',          icon: 'heart',   role: 'Holds sodium and water; drives blood pressure.' },
    { k: 'vitaminD',    label: 'Vitamin D hormone',    icon: 'shield',  role: 'Calcitriol, made from vitamin D: calcium, bones, muscle and immunity.' }
  ];

  /* Ingredient detection from names, for whole foods and live products with an
     ingredient text. Packaged products from the pack carry OffMap flags. */
  const NAME_SIGNALS = {
    FLAX: /flax|linseed|leinsamen|leinsaat|leinöl/,
    MINT: /peppermint|spearmint|pfefferminz|minze|minztee|mint tea/,
    HOPS: /\bbeer\b|\bbier\b|weizenbier|pils|hefeweizen|radler|hopfen|\bhops?\b/,
    CINNAMON: /cinnamon|\bzimt/,
    GINGER: /ginger|ingwer/,
    TURMERIC: /turmeric|kurkuma|curcuma|curcumin/,
    GREEN_TEA: /green tea|grüntee|grüner tee|matcha/,
    COCOA: /cocoa|kakao|dark chocolate|zartbitter|edelbitter/,
    GARLIC: /garlic|knoblauch/,
    CRUCIFEROUS: /broccoli|brokkoli|\bkale\b|grünkohl|cabbage|rotkohl|weißkohl|weisskohl|cauliflower|blumenkohl|brussels|rosenkohl|kohlrabi|rocket|rucola|watercress|bok choy|pak choi|sauerkraut|radieschen|radish/,
    MILK_PROTEIN: /whey|casein|milk protein|molkenprotein|milcheiweiß|\bquark|skyr|\bmilk\b|\bmilch|yogurt|yoghurt|joghurt|kefir|buttermilch|cottage cheese|hüttenkäse/,
    BETA_GLUCAN: /\boats?\b|\boat |hafer|barley|gerste|porridge|oatmeal/,
    OILY_FISH: /salmon|lachs|mackerel|makrele|herring|hering|sardine|anchov|sardelle|trout|forelle|fish oil|fischöl|omega-3/,
    TART_CHERRY: /tart cherr|sauerkirsch|montmorency/,
    ASHWAGANDHA: /ashwagandha|withania/,
    FENUGREEK: /fenugreek|bockshornklee/,
    TRIBULUS: /tribulus/,
    MACA: /\bmaca\b/
  };

  /** Everything known about the food's ingredients, as a set of signal names. */
  function signals(food) {
    const F = (window.OffMap && OffMap.FLAG) || {};
    const flags = typeof food.flags === 'number' ? food.flags : 0;
    const out = new Set();
    Object.keys(F).forEach(k => { if (flags & F[k]) out.add(k); });
    const text = [food.name, food.search, food.ingredientsText].filter(Boolean).join(' ').toLowerCase();
    Object.keys(NAME_SIGNALS).forEach(k => { if (NAME_SIGNALS[k].test(text)) out.add(k); });
    if (out.has('ADAPTOGEN')) {
      ['ASHWAGANDHA', 'FENUGREEK', 'TRIBULUS', 'MACA'].forEach(k => { if (NAME_SIGNALS[k].test(text)) out.add(k); });
    }
    // Whole dairy is milk protein; plain milk fat (butter, cream) is not.
    if (food.cat === 'Dairy & Eggs' && /egg|butter|cream|sahne|ghee/i.test(food.name || '') && !/protein|whey/i.test(text)) out.delete('MILK_PROTEIN');
    return out;
  }

  /**
   * Hormone effects of `grams` of `food`.
   * Returns [{ k, label, icon, role, dir, level, tone, items: [{ dir, strength,
   *   text, evidence, src[], tone }] }] — only hormones with something to say.
   */
  function forFood(food, grams) {
    if (!food || !food.n) return [];
    const g = grams > 0 ? grams : 100;
    const n = food.n;
    const amt = k => (Number(n[k]) || 0) * g / 100;
    const sig = signals(food);
    const isDrink = food.unit === 'ml' || food.cat === 'Drinks';
    const supplement = food.kind === 'supplement';
    const nova = window.Quality ? Quality.processing(food).nova : 0;
    const by = {};
    /** dir: up | down | support | neutral; tone: good | info | caution | warn */
    const add = (k, dir, strength, tone, evidence, text, src) =>
      (by[k] = by[k] || []).push({ dir, strength, tone, evidence, text, src: src || [] });

    const avail = Math.max(0, amt('carbs') - amt('fiber'));
    const gl = amt('gl') || (food.gi > 0 ? 0 : null);
    const protein = amt('protein'), fiber = amt('fiber'), free = amt('freesugar');
    const caf = amt('caffeine'), alc = amt('alcohol'), iso = amt('isoflavones');
    const gly = amt('glycyrrhizin') || (sig.has('LICORICE') ? 0.001 : 0);

    /* ---------------- insulin ---------------- */
    if (gl !== null && gl >= 20) add('insulin', 'up', 3, 'caution', 'strong', `A big glucose load (glycemic load ${Math.round(gl)}) brings a large insulin surge.`, ['gi-tables']);
    else if (gl !== null && gl >= 11) add('insulin', 'up', 2, 'info', 'strong', `A moderate glucose load (glycemic load ${Math.round(gl)}) brings a moderate insulin response.`, ['gi-tables']);
    else if (food.gi > 0 && avail >= 10) add('insulin', 'up', 1, 'good', 'strong', `Slowly absorbed carbohydrate (glycemic load ${Math.round(gl || 0)}): a gentle insulin response.`, ['gi-tables']);
    else if (!(food.gi > 0) && avail >= 25) add('insulin', 'up', avail >= 50 ? 3 : 2, 'info', 'moderate', `${Math.round(avail)} g of digestible carbohydrate raises insulin; how much depends on how fast it is absorbed.`, ['gi-tables']);
    if (sig.has('MILK_PROTEIN') && protein >= 8) add('insulin', 'up', protein >= 20 ? 2 : 1, 'info', 'strong', 'Milk proteins — whey above all — trigger far more insulin than their sugar content suggests (high insulin index). Useful after training, worth knowing otherwise.', ['holt-1997']);
    else if (protein >= 25) add('insulin', 'up', 1, 'info', 'moderate', 'A large protein portion triggers a modest insulin and glucagon release.', ['holt-1997']);
    if (sig.has('BETA_GLUCAN') && fiber >= 3) add('insulin', 'down', 1, 'good', 'strong', 'Oat and barley beta-glucan thickens the gut contents and blunts the blood-sugar and insulin rise.', ['efsa-betaglucan']);
    else if (fiber >= 6) add('insulin', 'down', 1, 'good', 'moderate', `${Math.round(fiber)} g of fibre slows sugar absorption and flattens the insulin curve.`, ['reynolds-2019']);
    if (sig.has('CINNAMON')) add('insulin', 'down', 1, 'good', 'limited', 'Cinnamon slightly improved fasting blood sugar in diabetes trials — at 1–6 g a day, more than a sprinkle.', ['allen-2013']);
    if (sig.has('SWEETENER') && (n.kcal || 0) < 20) add('insulin', 'neutral', 0, 'info', 'moderate', 'Non-sugar sweeteners do not raise insulin directly, though some changed gut bacteria and glucose tolerance in a trial.', ['suez-2022']);

    /* ---------------- fullness and hunger ---------------- */
    if (protein >= 20) {
      add('satiety', 'up', 2, 'good', 'strong', `${Math.round(protein)} g of protein releases the fullness hormones PYY and GLP-1 more than carbohydrate or fat.`, ['batterham-2006']);
      add('ghrelin', 'down', 2, 'good', 'moderate', 'A protein-rich meal keeps the hunger hormone ghrelin suppressed for longer.', ['blom-2006']);
    } else if (protein >= 10) {
      add('satiety', 'up', 1, 'good', 'strong', `${Math.round(protein)} g of protein adds to fullness signalling.`, ['batterham-2006']);
    }
    if (fiber >= 5) {
      add('satiety', 'up', 1, 'good', 'moderate', 'Gut bacteria ferment fibre into short-chain fatty acids that release GLP-1 and PYY.', ['chambers-2015']);
      add('ghrelin', 'down', 1, 'good', 'limited', 'Fibre-rich food keeps hunger down for longer.', ['reynolds-2019']);
    }
    if (isDrink && free >= 10) {
      add('satiety', 'down', 1, 'caution', 'moderate', 'Sugar in a drink barely registers in the fullness hormones — the calories add up without filling you.', ['dimeglio-2000']);
      add('ghrelin', 'up', 1, 'caution', 'limited', 'Fructose from sugary drinks suppresses ghrelin less than other carbohydrate.', ['teff-2004']);
    }
    if (gl !== null && gl >= 25) add('ghrelin', 'up', 1, 'caution', 'limited', 'After a big glucose spike, blood sugar often dips 2–3 hours later and hunger returns early.', ['ludwig-1999']);
    if (nova === 4 && !supplement) add('satiety', 'down', 1, 'caution', 'moderate', 'On an ultra-processed diet, people had lower PYY, higher ghrelin and ate about 500 kcal a day more.', ['hall-2019']);

    /* ---------------- stress hormones ---------------- */
    if (caf >= 40) {
      add('cortisol', 'up', caf >= 200 ? 2 : 1, 'caution', 'moderate', `${Math.round(caf)} mg of caffeine raises cortisol for a few hours — less so in daily coffee drinkers.`, ['lovallo-2005']);
      add('adrenaline', 'up', caf >= 200 ? 2 : 1, 'info', 'strong', `${Math.round(caf)} mg of caffeine releases adrenaline: faster heart, more alertness, more fat released for fuel.`, ['robertson-1978']);
    }
    if (alc >= 10) add('cortisol', 'up', alc >= 30 ? 2 : 1, 'caution', 'moderate', 'Alcohol raises cortisol, and regular drinking keeps it higher through the day.', ['badrick-2008']);
    if (gly > 0) {
      add('cortisol', 'up', 2, 'caution', 'moderate', 'Licorice blocks the enzyme that inactivates cortisol in the kidney (11β-HSD2), so cortisol acts longer and harder.', ['stewart-1987']);
      add('aldosterone', 'up', amt('glycyrrhizin') >= 100 ? 3 : 2, 'warn', 'moderate', 'With that enzyme blocked, cortisol acts like aldosterone: the body holds sodium, loses potassium and blood pressure rises. Advised limit: 100 mg glycyrrhizin a day.', ['scf-2003', 'stewart-1987']);
    }
    if (sig.has('ASHWAGANDHA') || (sig.has('ADAPTOGEN') && /ashwagandha|withania/i.test(food.name || ''))) {
      add('cortisol', 'down', 1, 'good', 'limited', 'Ashwagandha root extract lowered cortisol by about a quarter in small 8-week trials. Rare cases of liver injury are reported.', ['chandrasekhar-2012']);
    }

    /* ---------------- sex hormones ---------------- */
    if (alc >= 10) {
      add('testosterone', 'down', alc >= 30 ? 2 : 1, 'caution', 'moderate', 'Even moderate daily drinking lowered testosterone slightly in a controlled trial; heavy drinking lowers it markedly.', ['sierksma-2004']);
      add('estrogen', 'up', alc >= 30 ? 2 : 1, 'caution', 'moderate', 'Alcohol raises estrogen levels — one of the ways it increases breast cancer risk.', ['dorgan-2001']);
    }
    if (gly > 0) add('testosterone', 'down', 1, 'caution', 'limited', 'Daily licorice lowered testosterone in a small study of men.', ['armanini-1999']);
    if (free >= 40 || (gl !== null && gl >= 35)) add('testosterone', 'down', 1, 'info', 'limited', 'A large sugar load briefly lowered testosterone by about a quarter in men (it recovered within hours).', ['caronia-2013']);
    if (sig.has('MINT')) add('testosterone', 'down', 1, 'info', 'limited', 'Spearmint tea lowered free testosterone in women with PCOS in a small trial; peppermint is thought to act similarly but is less studied.', ['grant-2010']);
    if (sig.has('FLAX')) {
      add('testosterone', 'down', 1, 'info', 'limited', 'Flaxseed lignans lowered testosterone in a case study and small trials — mainly relevant at 30 g a day or more.', ['nowak-2007']);
      add('estrogen', 'neutral', 0, 'info', 'limited', 'Flax lignans are weak plant estrogens; in women they lengthened the luteal phase without harm.', ['phipps-1993']);
    }
    if (iso >= 10) {
      add('testosterone', 'neutral', 0, 'good', 'strong', `${Math.round(iso)} mg of soy isoflavones: dozens of clinical trials found no effect on testosterone or estrogen in men.`, ['hamilton-reeves-2010', 'reed-2021']);
      add('estrogen', 'neutral', 0, 'info', 'strong', 'Soy isoflavones bind estrogen receptors weakly; at food intakes they do not measurably change hormone levels.', ['reed-2021']);
    }
    if (sig.has('HOPS')) add('estrogen', 'up', 1, 'info', 'limited', 'Hops contain 8-prenylnaringenin, one of the most potent plant estrogens — though beer carries only small amounts.', ['milligan-1999']);
    if (sig.has('CRUCIFEROUS') && g >= 50) add('estrogen', 'support', 1, 'good', 'limited', 'Cabbage-family vegetables shift estrogen breakdown toward its less active forms (via indole-3-carbinol).', ['fowke-2000']);
    if (fiber >= 8) add('estrogen', 'down', 1, 'info', 'limited', 'High fibre intake binds estrogen in the gut so more is excreted.', ['gaskins-2009']);
    if (amt('zn') >= 4) add('testosterone', 'support', 1, 'good', 'limited', `${Math.round(amt('zn') * 10) / 10} mg zinc — needed to make testosterone; it restores low levels but does not boost normal ones.`, ['prasad-1996']);
    if (amt('vitD') >= 5) add('testosterone', 'support', 1, 'good', 'limited', 'Vitamin D raised testosterone in deficient men in one trial; there is no effect when levels are already normal.', ['pilz-2011']);
    if (sig.has('FENUGREEK')) add('testosterone', 'up', 1, 'info', 'limited', 'Fenugreek extract slightly raised total testosterone in a meta-analysis of small trials.', ['mansoori-2020']);
    if (sig.has('ASHWAGANDHA')) add('testosterone', 'up', 1, 'info', 'limited', 'Ashwagandha raised testosterone modestly in overweight older men in a crossover trial.', ['lopresti-2019']);
    if (sig.has('TRIBULUS') || sig.has('MACA')) add('testosterone', 'neutral', 0, 'info', 'moderate', 'Tribulus and maca do not raise testosterone in human trials, whatever the packaging says; maca may help libido.', ['qureshi-2014']);

    /* ---------------- thyroid ---------------- */
    const iod = amt('iodine');
    if (iod >= 600) add('thyroid', 'up', 2, 'warn', 'strong', `${Math.round(iod)} µg iodine — above the 600 µg daily upper limit. Too much iodine can disturb the thyroid as much as too little.`, ['efsa-iodine-ul']);
    else if (iod >= 30) add('thyroid', 'support', iod >= 75 ? 2 : 1, 'good', 'strong', `${Math.round(iod)} µg iodine — the raw material for the thyroid hormones T3 and T4.`, ['efsa-iodine']);
    if (amt('se') >= 20) add('thyroid', 'support', 1, 'good', 'strong', 'Selenium switches inactive T4 into active T3.', ['efsa-selenium']);
    if (iso >= 20) add('thyroid', 'neutral', 0, 'info', 'moderate', 'Soy does not impair thyroid function when iodine intake is adequate — but take thyroid medication about 4 hours apart from soy.', ['messina-2006']);
    if (sig.has('CRUCIFEROUS') && g >= 150) add('thyroid', 'neutral', 0, 'info', 'moderate', 'Cabbage-family goitrogens only matter in iodine deficiency or at very large raw amounts.', ['felker-2016']);

    /* ---------------- sleep ---------------- */
    if (caf >= 40) add('melatonin', 'down', caf >= 150 ? 2 : 1, 'caution', 'moderate', 'Caffeine in the evening delays the melatonin rise by around 40 minutes and shortens deep sleep.', ['burke-2015', 'drake-2013']);
    if (alc >= 10) add('melatonin', 'down', 1, 'caution', 'moderate', 'Alcohol helps you fall asleep but suppresses melatonin and fragments the second half of the night.', ['ebrahim-2013']);
    if (sig.has('TART_CHERRY')) add('melatonin', 'up', 1, 'good', 'limited', 'Tart cherries contain melatonin; their juice raised melatonin and sleep time in a small trial.', ['howatson-2012']);

    /* ---------------- growth ---------------- */
    if (sig.has('MILK_PROTEIN') && protein >= 8) add('igf1', 'up', protein >= 20 ? 2 : 1, 'info', 'moderate', 'Milk and dairy protein raise IGF-1 — good for muscle building; very high long-term IGF-1 is linked to prostate and breast cancer.', ['romo-ventura-2020']);
    else if (protein >= 30) add('igf1', 'up', 1, 'info', 'moderate', 'A large protein intake supports IGF-1 and muscle protein synthesis.', ['moore-2009']);

    /* ---------------- vitamin D ---------------- */
    if (amt('vitD') >= 2.5) add('vitaminD', 'support', amt('vitD') >= 10 ? 2 : 1, 'good', 'strong', `${Math.round(amt('vitD') * 10) / 10} µg vitamin D — the precursor of the hormone calcitriol.`, ['efsa-vitd']);
    else if (sig.has('OILY_FISH') && g >= 50 && !supplement) add('vitaminD', 'support', 1, 'good', 'strong', 'Oily fish is one of the few natural food sources of vitamin D.', ['efsa-vitd']);

    /* ---------------- assemble ---------------- */
    const TONE = { warn: 0, caution: 1, good: 2, info: 3 };
    return LIST.filter(h => by[h.k]).map(h => {
      const items = by[h.k].sort((a, b) => b.strength - a.strength || TONE[a.tone] - TONE[b.tone]);
      const up = items.filter(i => i.dir === 'up').reduce((s, i) => s + i.strength, 0);
      const down = items.filter(i => i.dir === 'down').reduce((s, i) => s + i.strength, 0);
      const support = items.some(i => i.dir === 'support');
      let dir = 'neutral';
      if (up && down) dir = up > down ? 'up' : down > up ? 'down' : 'mixed';
      else if (up) dir = 'up';
      else if (down) dir = 'down';
      else if (support) dir = 'support';
      const level = Math.min(3, Math.max(up, down, support ? 1 : 0));
      // The tone of the strongest reason pointing the net way decides the colour.
      const lead = items.find(i => i.dir === dir) || items[0];
      return Object.assign({}, h, { dir, level, tone: lead.tone, items });
    });
  }

  /**
   * The day's hormone picture: every food's hormone effects, merged per hormone
   * with the foods that caused them. `resolve(entry)` -> food or null.
   */
  function forDay(entries, resolve) {
    const merged = {};
    (entries || []).forEach(e => {
      if (!e.n || !(e.grams > 0)) return;
      const f = resolve ? resolve(e) : null;
      const food = Object.assign({}, f || { name: e.name }, { n: Nutrition.mul(e.n, 100 / e.grams) });
      forFood(food, e.grams).forEach(h => {
        const m = merged[h.k] || (merged[h.k] = Object.assign({}, h, { items: [], foods: [], score: 0 }));
        h.items.forEach(i => m.items.push(Object.assign({ food: e.name }, i)));
        if (m.foods.indexOf(e.name) === -1) m.foods.push(e.name);
        m.score += h.dir === 'up' ? h.level : h.dir === 'down' ? -h.level : 0;
      });
    });
    return LIST.filter(h => merged[h.k]).map(h => {
      const m = merged[h.k];
      const up = m.items.filter(i => i.dir === 'up').reduce((s, i) => s + i.strength, 0);
      const down = m.items.filter(i => i.dir === 'down').reduce((s, i) => s + i.strength, 0);
      m.dir = up && down ? (up > down * 1.5 ? 'up' : down > up * 1.5 ? 'down' : 'mixed') : up ? 'up' : down ? 'down'
        : m.items.some(i => i.dir === 'support') ? 'support' : 'neutral';
      m.level = Math.min(3, Math.max(1, Math.round(Math.max(up, down) / 2)));
      const lead = m.items.filter(i => i.dir === m.dir).sort((a, b) => b.strength - a.strength)[0] || m.items[0];
      m.tone = lead.tone;
      return m;
    });
  }

  /** Arrow glyph for a direction and strength. */
  function arrow(dir, level) {
    const n = Math.max(1, Math.min(3, level || 1));
    if (dir === 'up') return '↑'.repeat(n);
    if (dir === 'down') return '↓'.repeat(n);
    if (dir === 'mixed') return '↕';
    if (dir === 'support') return '✓';
    return '=';
  }
  const DIR_TEXT = { up: 'Raises', down: 'Lowers', mixed: 'Mixed', support: 'Supports', neutral: 'No real effect' };

  if (window.Body) Object.assign(Body.SOURCES, SOURCES);
  window.Hormones = { forFood, forDay, signals, arrow, LIST, DIR_TEXT, SOURCES };
})();
